import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import {AxiosResponse} from "axios"
import { getCategories, getPosts } from '../services'
import ICollectionResponse, { ICategory, IPost } from '../types'
import { Tabs } from '../components'
import Posts from '../components/Posts'

interface IpropTypes {
  categories: ICategory[],
  posts: IPost[]
}

const Home: NextPage<IpropTypes> = ({categories = [], posts = []}) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Tabs */}
      <Tabs categories={categories} />

      {/* Trading posts */}

      {/* Posts */}
      <Posts posts={posts} />
    </>
  )
}

//Server side rendering
export const getServerSideProps: GetServerSideProps = async () => {
  //get posts 
  const {data: posts} :AxiosResponse<ICollectionResponse<IPost[]>> = await getPosts()
  
  //get categories 
  const {data : categories} : AxiosResponse<ICollectionResponse<ICategory[]>> = await getCategories()
  
  return {
    props: {
      categories: categories.data.filter(category => category.name !== "Uncategorized"),
      posts: posts.data
    }
  }
}

export default Home
