import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import {AxiosResponse} from "axios"
import service from '../services'
import ICollectionResponse, { ICategory } from '../types'

interface IpropTypes {
  categories: {
    items: ICategory[]
  }
}

const Home: NextPage<IpropTypes> = ({categories}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className="text-primary">
      Hello world!
    </h2>
        
    </>
  )
}

//Server side rendering
export const getServerSideProps: GetServerSideProps = async () => {
  
  const {data : categories} : AxiosResponse<ICollectionResponse<ICategory[]>> = await service.category.getCategories()
  
  return {
    props: {
      categories: {
        items: categories.data
      }
    }
  }
}

export default Home
